events { worker_connections 1024; }
http {
    client_body_temp_path /tmp/nginx_client_body;
    proxy_temp_path /tmp/nginx_proxy;
    fastcgi_temp_path /tmp/nginx_fastcgi;
    uwsgi_temp_path /tmp/nginx_uwsgi;
    scgi_temp_path /tmp/nginx_scgi;
    proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=wcd:10m max_size=10m;
    server {
        listen 8080;
        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot|pdf|xml|txt|json|webp|bmp)(\?.*)?$ {
            proxy_cache wcd;
            proxy_cache_valid 200 60m;
            proxy_pass http://127.0.0.1:8081;
            add_header X-Cache-Status $upstream_cache_status;
            add_header X-Config-Version "vuln_1.0";
        }
        location / {
            proxy_pass http://127.0.0.1:8081;
            add_header X-Config-Version "vuln_1.0";
        }
    }
}




